const recipes = [
  {
    title: "Spaghetti Bolognese",
    slug: "spaghetti-bolognese",
    ingredients: [
      "400g spaghetti",
      "500g ground beef",
      "800g tomato sauce",
      "1 large onion, diced",
      "4 garlic cloves, minced",
      "2 tbsp olive oil",
      "1 tsp salt",
      "1/2 tsp black pepper",
      "1 tsp dried oregano",
    ],
    instructions: [
      "Bring a large pot of salted water to boil and cook spaghetti according to package instructions until al dente.",
      "Meanwhile, heat olive oil in a large pan over medium heat. Add onions and sauté until translucent (about 5 minutes).",
      "Add minced garlic and cook for 1 minute until fragrant.",
      "Increase heat to medium-high and add ground beef. Break it apart with a wooden spoon and cook until browned (about 7-8 minutes).",
      "Stir in tomato sauce, salt, pepper, and oregano. Reduce heat to low and simmer for 15-20 minutes, stirring occasionally.",
      "Drain spaghetti and toss with a little olive oil. Serve topped with the Bolognese sauce and grated Parmesan cheese.",
    ],
    notes:
      "A classic Italian comfort food that's perfect for family dinners. The key is to let the sauce simmer to develop deep flavors. For an authentic touch, add a splash of red wine to the sauce.",
    servings: 4,
    time: 30,
    category: "Italian",
    img: "https://images.unsplash.com/photo-1622973536968-3ead9e780960?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c3BhZ2hldHRpJTIwYm9sb2duZXNlfGVufDB8fDB8fHww",
    rating: 4.5,
  },
  {
    title: "Chicken Curry",
    slug: "chicken-curry",
    ingredients: [
      "800g chicken thighs, cut into pieces",
      "2 onions, finely chopped",
      "4 garlic cloves, minced",
      "2 tbsp fresh ginger, grated",
      "3 tbsp curry powder",
      "400ml coconut milk",
      "2 tbsp vegetable oil",
      "1 tsp salt",
      "1/2 tsp chili flakes (optional)",
      "Fresh coriander for garnish",
    ],
    instructions: [
      "Heat oil in a large pot over medium heat. Add onions and cook until golden (about 8 minutes).",
      "Add garlic and ginger, cooking for 1 minute until fragrant.",
      "Stir in curry powder and cook for 30 seconds to toast the spices.",
      "Add chicken pieces and cook for 5 minutes, stirring to coat with spices.",
      "Pour in coconut milk and bring to a gentle simmer. Cover and cook for 25-30 minutes until chicken is tender.",
      "Season with salt and chili flakes. Garnish with fresh coriander before serving with steamed rice.",
    ],
    notes:
      "This aromatic curry is a staple in Indian households. For extra richness, you can add 2 tablespoons of yogurt or tomato paste. The longer it simmers, the more flavorful it becomes!",
    servings: 4,
    time: 40,
    category: "Indian",
    img: "https://plus.unsplash.com/premium_photo-1723708871094-2c02cf5f5394?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y2hpY2tlbiUyMGN1cnJ5fGVufDB8fDB8fHww",
    rating: 4.7,
  },
  {
    title: "Pancakes",
    slug: "pancakes",
    ingredients: [
      "200g all-purpose flour",
      "300ml milk",
      "1 large egg",
      "2 tbsp melted butter",
      "2 tbsp sugar",
      "1 tsp baking powder",
      "1/2 tsp salt",
      "1 tsp vanilla extract",
    ],
    instructions: [
      "In a large bowl, whisk together flour, sugar, baking powder and salt.",
      "In another bowl, beat the egg, then add milk, melted butter and vanilla.",
      "Pour wet ingredients into dry ingredients and stir until just combined (small lumps are okay).",
      "Heat a non-stick pan over medium heat and lightly grease with butter.",
      "Pour 1/4 cup batter for each pancake. Cook until bubbles form on surface (about 2 minutes).",
      "Flip and cook for another 1-2 minutes until golden brown.",
      "Serve warm with maple syrup, fresh berries or whipped cream.",
    ],
    notes:
      "Perfect fluffy pancakes every time! Don't overmix the batter - this keeps them light. For extra-fluffy pancakes, separate the egg and fold in whipped egg white at the end.",
    servings: 2,
    time: 15,
    category: "Breakfast",
    img: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cGFuY2FrZXN8ZW58MHx8MHx8fDA%3D",
    rating: 4.3,
  },
  {
    title: "Grilled Cheese Sandwich",
    slug: "grilled-cheese-sandwich",
    ingredients: [
      "2 slices of sourdough bread",
      "100g cheddar cheese, sliced",
      "2 tbsp butter, softened",
      "1/4 tsp garlic powder (optional)",
      "1/4 tsp paprika (optional)",
    ],
    instructions: [
      "Butter one side of each bread slice. If using, mix garlic powder and paprika into the butter.",
      "Heat a skillet over medium-low heat.",
      "Place one bread slice butter-side down in the skillet. Layer with cheese slices.",
      "Top with second bread slice, butter-side up.",
      "Cook for 3-4 minutes until golden brown, then carefully flip.",
      "Cook for another 3-4 minutes until second side is golden and cheese is melted.",
      "Remove from pan, let rest for 1 minute, then slice diagonally and serve.",
    ],
    notes:
      "The ultimate comfort food! For restaurant-quality results, use a combination of cheeses (try adding some Gruyère). Cooking low and slow ensures perfect melting without burning the bread.",
    servings: 1,
    time: 10,
    category: "Snack",
    img: "https://images.unsplash.com/photo-1475090169767-40ed8d18f67d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fEdyaWxsZWQlMjBjaGVlc2UlMjBzYW5kd2l0Y2h8ZW58MHx8MHx8fDA%3D",
    rating: 4.8,
  },
  {
    title: "Caesar Salad",
    slug: "caesar-salad",
    ingredients: [
      "1 large romaine lettuce, chopped",
      "100g croutons",
      "50g parmesan cheese, shaved",
      "150ml Caesar dressing",
      "1 tbsp lemon juice",
      "1 clove garlic, minced",
      "6 anchovy fillets (optional)",
      "Freshly ground black pepper",
    ],
    instructions: [
      "In a large bowl, whisk together Caesar dressing, lemon juice and minced garlic.",
      "Add chopped romaine lettuce and toss gently to coat all leaves.",
      "Add croutons and toss lightly again.",
      "Transfer to serving plates and top with shaved parmesan.",
      "If using, arrange anchovy fillets on top.",
      "Finish with freshly ground black pepper and serve immediately.",
    ],
    notes:
      "A classic that never goes out of style. For the best results, chill your salad bowls beforehand. Making your own croutons from day-old bread elevates this dish tremendously.",
    servings: 2,
    time: 10,
    category: "Salad",
    img: "https://images.unsplash.com/photo-1746211108786-ca20c8f80ecd?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8Y2VzYXIlMjBzYWxhZHxlbnwwfHwwfHx8MA%3D%3D",
    rating: 4.2,
  },
  {
    title: "Vegetable Stir Fry",
    slug: "vegetable-stir-fry",
    ingredients: [
      "2 cups mixed vegetables (bell peppers, broccoli, carrots, snap peas)",
      "2 tbsp soy sauce",
      "1 tbsp oyster sauce",
      "2 garlic cloves, minced",
      "1 tbsp fresh ginger, grated",
      "1 tbsp sesame oil",
      "2 tbsp vegetable oil",
      "1 tsp cornstarch dissolved in 2 tbsp water",
      "1 tsp honey or sugar",
      "Sesame seeds for garnish",
    ],
    instructions: [
      "Prepare all vegetables by cutting into uniform bite-sized pieces.",
      "Heat vegetable oil in a wok or large skillet over high heat.",
      "Add garlic and ginger, stir for 15 seconds until fragrant.",
      "Add harder vegetables first (carrots, broccoli) and stir fry for 2 minutes.",
      "Add remaining vegetables and continue stir frying for 3-4 minutes.",
      "In a small bowl, mix soy sauce, oyster sauce, and honey.",
      "Pour sauce over vegetables and toss to coat evenly.",
      "Add cornstarch mixture and stir until sauce thickens (about 1 minute).",
      "Drizzle with sesame oil, garnish with sesame seeds, and serve immediately with rice.",
    ],
    notes:
      "The secret to perfect stir fry is high heat and quick cooking. Have all ingredients prepped before you start cooking. For protein, add tofu, chicken, or shrimp in step 4.",
    servings: 3,
    time: 15,
    category: "Vegetarian",
    img: "https://plus.unsplash.com/premium_photo-1664475934279-2631a25c42ce?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dmVnZXRhYmxlJTIwc3RpciUyMGZyeXxlbnwwfHwwfHx8MA%3D%3D",
    rating: 4.4,
  },
  {
    title: "Beef Tacos",
    slug: "beef-tacos",
    ingredients: [
      "8 taco shells or small tortillas",
      "500g ground beef",
      "1 packet taco seasoning",
      "1 cup lettuce, shredded",
      "1 tomato, diced",
      "1/2 cup cheddar cheese, shredded",
      "1/4 cup sour cream",
      "1/4 cup salsa",
      "1 avocado, sliced",
      "1 lime, cut into wedges",
      "2 tbsp vegetable oil",
    ],
    instructions: [
      "Heat oil in a skillet over medium-high heat. Add ground beef and cook until browned, breaking it apart as it cooks (about 7-8 minutes).",
      "Drain excess fat, then add taco seasoning and 1/2 cup water. Simmer for 5 minutes until thickened.",
      "Meanwhile, warm taco shells according to package directions.",
      "Prepare all toppings: shred lettuce, dice tomato, shred cheese, slice avocado.",
      "Assemble tacos: start with beef, then add toppings as desired.",
      "Serve with lime wedges for squeezing over the top.",
    ],
    notes:
      "Taco night is always a hit! For authentic flavor, toast your tortillas briefly on a dry skillet. Set up a taco bar with various toppings for a fun, interactive meal.",
    servings: 4,
    time: 20,
    category: "Mexican",
    img: "https://images.unsplash.com/photo-1640983743761-4f0e0204bc58?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmVlZiUyMHRhY29zfGVufDB8fDB8fHww",
    rating: 4.6,
  },
  {
    title: "Chocolate Cake",
    slug: "chocolate-cake",
    ingredients: [
      "200g all-purpose flour",
      "200g sugar",
      "75g cocoa powder",
      "1 tsp baking powder",
      "1 tsp baking soda",
      "1/2 tsp salt",
      "2 large eggs",
      "150ml milk",
      "150ml vegetable oil",
      "2 tsp vanilla extract",
      "150ml boiling water",
      "For frosting: 200g butter, 400g powdered sugar, 100g cocoa powder, 5 tbsp milk",
    ],
    instructions: [
      "Preheat oven to 180°C (350°F). Grease and line two 20cm round cake pans.",
      "In a large bowl, sift together flour, sugar, cocoa, baking powder, baking soda and salt.",
      "Add eggs, milk, oil and vanilla. Beat with mixer on medium speed for 2 minutes.",
      "Carefully stir in boiling water (batter will be thin).",
      "Divide batter evenly between prepared pans.",
      "Bake for 30-35 minutes until a toothpick comes out clean.",
      "Cool in pans for 10 minutes, then transfer to wire racks to cool completely.",
      "For frosting: Beat butter until creamy. Gradually add powdered sugar and cocoa, then milk until smooth.",
      "Frost cooled cake layers, stacking with frosting in between and covering the top and sides.",
    ],
    notes:
      "This moist, rich cake is a chocolate lover's dream. The boiling water helps bloom the cocoa for maximum flavor. For special occasions, add chocolate shavings or fresh berries as decoration.",
    servings: 8,
    time: 45,
    category: "Dessert",
    img: "https://images.unsplash.com/photo-1586985289906-406988974504?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2hvY29sYXRlJTIwY2FrZXxlbnwwfHwwfHx8MA%3D%3D",
    rating: 4.9,
  },
  {
    title: "Omelette",
    slug: "omelette",
    ingredients: [
      "3 large eggs",
      "2 tbsp milk",
      "50g cheese (cheddar, feta, or your choice), cubed or crumbled",
      "1/4 bell pepper, diced",
      "2 tbsp onion, finely chopped",
      "1 tbsp butter",
      "Salt and pepper to taste",
      "Fresh herbs (chives, parsley) for garnish",
    ],
    instructions: [
      "In a bowl, whisk eggs with milk, salt and pepper until well combined.",
      "Heat butter in a non-stick skillet over medium heat.",
      "Add onions and bell pepper, sauté for 2 minutes until slightly softened.",
      "Pour egg mixture into the pan. As edges set, gently push cooked portions toward center with a spatula.",
      "When eggs are nearly set but still slightly runny on top (after about 2 minutes), sprinkle cheese over one half.",
      "Carefully fold omelette in half with spatula. Cook for another 30 seconds.",
      "Slide onto plate, garnish with fresh herbs, and serve immediately.",
    ],
    notes:
      "Mastering the omelette is a fundamental cooking skill. The key is controlling the heat - not too high! For a French-style omelette, keep the center slightly soft and don't brown the outside.",
    servings: 2,
    time: 10,
    category: "Breakfast",
    img: "https://images.unsplash.com/photo-1677137261161-0095c10418ef?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG9tZWxldHRlfGVufDB8fDB8fHww",
    rating: 4.1,
  },
  {
    title: "Margherita Pizza",
    slug: "margherita-pizza",
    ingredients: [
      "1 pizza dough (store-bought or homemade)",
      "150ml tomato sauce",
      "200g fresh mozzarella, sliced",
      "Fresh basil leaves",
      "2 tbsp olive oil",
      "Salt to taste",
      "1 clove garlic, minced (optional)",
      "Red pepper flakes (optional)",
    ],
    instructions: [
      "Preheat oven to 240°C (475°F) with pizza stone or baking sheet inside.",
      "Roll out dough on floured surface to desired thickness (about 30cm diameter).",
      "Transfer dough to parchment paper. Brush with 1 tbsp olive oil.",
      "Spread tomato sauce evenly over dough, leaving small border for crust.",
      "Arrange mozzarella slices over sauce.",
      "Carefully transfer pizza (with parchment) onto preheated stone/sheet.",
      "Bake for 10-12 minutes until crust is golden and cheese is bubbly.",
      "Remove from oven, immediately top with fresh basil leaves.",
      "Drizzle with remaining olive oil, optional garlic, and red pepper flakes.",
      "Let rest 2 minutes before slicing and serving.",
    ],
    notes:
      "The simplicity of this Neapolitan classic highlights quality ingredients. Use the best tomatoes you can find for the sauce. For authentic char, cook at the highest temperature your oven allows.",
    servings: 2,
    time: 20,
    category: "Italian",
    img: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TWFyZ2hlcml0YSUyMFBpenphfGVufDB8fDB8fHww",
    rating: 4.8,
  },
  {
    title: "Tomato Soup",
    slug: "tomato-soup",
    ingredients: [
      "1kg ripe tomatoes, quartered",
      "1 large onion, chopped",
      "4 garlic cloves, peeled",
      "500ml vegetable broth",
      "2 tbsp olive oil",
      "1 tsp sugar",
      "1 tsp salt",
      "1/2 tsp black pepper",
      "1/2 tsp dried basil",
      "1/2 cup heavy cream (optional)",
      "Fresh basil for garnish",
    ],
    instructions: [
      "Preheat oven to 200°C (400°F). Toss tomatoes, onion and garlic with olive oil on baking sheet.",
      "Roast for 30 minutes until vegetables are softened and slightly caramelized.",
      "Transfer roasted vegetables to a pot. Add vegetable broth, sugar, salt, pepper and dried basil.",
      "Bring to boil, then reduce heat and simmer for 15 minutes.",
      "Use immersion blender to puree soup until smooth (or carefully blend in batches in regular blender).",
      "Stir in cream if using, and adjust seasoning.",
      "Serve hot, garnished with fresh basil leaves and a drizzle of olive oil.",
    ],
    notes:
      "Roasting the tomatoes first intensifies their natural sweetness. This soup freezes beautifully - make a double batch! For a lighter version, omit the cream or substitute with coconut milk.",
    servings: 4,
    time: 25,
    category: "Soup",
    img: "https://images.unsplash.com/photo-1673021889619-0677506b56ac?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fHRvbWF0byUyMHNvdXB8ZW58MHx8MHx8fDA%3D",
    rating: 4.3,
  },
  {
    title: "BBQ Chicken",
    slug: "bbq-chicken",
    ingredients: [
      "8 chicken pieces (thighs and drumsticks)",
      "250ml BBQ sauce",
      "2 tbsp olive oil",
      "1 tsp smoked paprika",
      "1 tsp garlic powder",
      "1 tsp onion powder",
      "1/2 tsp salt",
      "1/2 tsp black pepper",
      "1 tbsp brown sugar",
      "1 tbsp apple cider vinegar",
    ],
    instructions: [
      "In a bowl, mix BBQ sauce with olive oil, paprika, garlic powder, onion powder, salt, pepper, brown sugar and vinegar.",
      "Place chicken in a large ziplock bag or bowl. Pour 3/4 of the marinade over chicken, reserving the rest.",
      "Marinate in refrigerator for at least 2 hours, preferably overnight.",
      "Preheat grill to medium heat (about 180°C/350°F). Oil the grates.",
      "Remove chicken from marinade (shake off excess) and place on grill.",
      "Grill for 25-30 minutes, turning occasionally, until internal temperature reaches 75°C (165°F).",
      "During last 5 minutes, brush with reserved marinade.",
      "Let rest 5 minutes before serving.",
    ],
    notes:
      "The key to perfect BBQ chicken is indirect heat - if using charcoal, pile coals on one side. For extra smoky flavor, add wood chips to your grill. Always use a meat thermometer for food safety.",
    servings: 4,
    time: 35,
    category: "Grill",
    img: "https://plus.unsplash.com/premium_photo-1692835633701-ad06af67cec7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8YmFyYmVjdWUlMjBDaGlja2VufGVufDB8fDB8fHww",
    rating: 4.7,
  },
  {
    title: "French Toast",
    slug: "french-toast",
    ingredients: [
      "8 slices thick bread (brioche or challah work best)",
      "4 large eggs",
      "300ml milk",
      "1 tsp vanilla extract",
      "1/2 tsp ground cinnamon",
      "2 tbsp sugar",
      "Pinch of salt",
      "Butter for cooking",
      "Maple syrup for serving",
      "Powdered sugar for dusting (optional)",
      "Fresh berries for serving (optional)",
    ],
    instructions: [
      "In a shallow dish, whisk together eggs, milk, vanilla, cinnamon, sugar and salt.",
      "Heat a large skillet or griddle over medium heat. Add 1 tbsp butter.",
      "Dip bread slices into egg mixture, allowing to soak for 15-20 seconds per side.",
      "Transfer soaked bread to hot skillet. Cook for 3-4 minutes per side until golden brown.",
      "Repeat with remaining bread, adding more butter as needed.",
      "Serve immediately with maple syrup, dusted with powdered sugar and fresh berries if desired.",
    ],
    notes:
      "Day-old bread works best as it absorbs more custard without falling apart. For decadent French toast, substitute half the milk with cream. Keep cooked slices warm in a 90°C (200°F) oven while finishing the batch.",
    servings: 2,
    time: 15,
    category: "Breakfast",
    img: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZnJlbmNoJTIwdG9hc3R8ZW58MHx8MHx8fDA%3D",
    rating: 4.5,
  },
  {
    title: "Burrito",
    slug: "burrito",
    ingredients: [
      "4 large flour tortillas",
      "300g cooked rice",
      "400g cooked black or pinto beans",
      "300g cooked chicken, beef or pork, shredded",
      "1 cup cheese, shredded",
      "1 avocado, sliced",
      "1/2 cup salsa",
      "1/2 cup sour cream",
      "1 tsp cumin",
      "1 tsp chili powder",
      "2 tbsp lime juice",
      "Fresh cilantro for garnish",
      "Oil for cooking",
    ],
    instructions: [
      "In a bowl, mix rice with lime juice, cumin and chili powder.",
      "Heat tortillas briefly to make them pliable (about 15 seconds per side in dry skillet).",
      "Layer each tortilla with rice, beans, meat, cheese, avocado, salsa and sour cream.",
      "Fold sides inward, then roll up tightly from the bottom.",
      "Optional: Heat a skillet with a little oil over medium heat. Place burritos seam-side down and cook for 2-3 minutes per side until golden and crispy.",
      "Serve with extra salsa, sour cream and fresh cilantro.",
    ],
    notes:
      "The perfect portable meal! For meal prep, wrap burritos tightly in foil and freeze. Reheat in oven at 180°C (350°F) for 20-25 minutes. Wet ingredients like salsa are best added fresh when serving.",
    servings: 1,
    time: 20,
    category: "Mexican",
    img: "https://plus.unsplash.com/premium_photo-1664478294917-c11274b9ce79?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YnVycml0b3xlbnwwfHwwfHx8MA%3D%3D",
    rating: 4.6,
  },
  {
    title: "Fried Rice",
    slug: "fried-rice",
    ingredients: [
      "3 cups cooked rice (preferably day-old)",
      "2 eggs, beaten",
      "1 cup mixed vegetables (peas, carrots, corn)",
      "2 green onions, chopped",
      "3 tbsp soy sauce",
      "1 tbsp oyster sauce",
      "1 tsp sesame oil",
      "2 tbsp vegetable oil",
      "1 tsp ginger, minced",
      "2 garlic cloves, minced",
      "1/2 tsp white pepper",
      "Cooked protein (chicken, shrimp, tofu) - optional",
    ],
    instructions: [
      "Heat 1 tbsp vegetable oil in wok or large skillet over high heat.",
      "Add beaten eggs and scramble until just set. Remove and set aside.",
      "Add remaining oil to wok. Sauté garlic and ginger for 15 seconds until fragrant.",
      "Add vegetables and stir fry for 2 minutes.",
      "Add rice, breaking up any clumps. Stir fry for 3 minutes until heated through.",
      "Add soy sauce, oyster sauce and white pepper. Toss to combine evenly.",
      "Return scrambled eggs to wok. Add green onions and sesame oil.",
      "If using, add cooked protein and heat through.",
      "Toss everything together and serve immediately.",
    ],
    notes:
      "The secret to perfect fried rice is using cold, day-old rice - fresh rice makes it mushy. High heat and quick cooking are essential. For authentic 'wok hei' flavor, cook in small batches if your stove isn't very powerful.",
    servings: 2,
    time: 15,
    category: "Asian",
    img: "https://images.unsplash.com/photo-1609570324378-ec0c4c9b6ba8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8ZnJpZWQlMjByaWNlfGVufDB8fDB8fHww",
    rating: 4.4,
  },
  {
    title: "Fish Curry",
    slug: "fish-curry",
    ingredients: [
      "600g firm white fish fillets (cod, halibut, snapper)",
      "1 onion, finely chopped",
      "2 tomatoes, chopped",
      "2 tbsp curry powder",
      "400ml coconut milk",
      "2 tbsp vegetable oil",
      "1 tbsp ginger, grated",
      "3 garlic cloves, minced",
      "1 green chili, sliced (optional)",
      "1 tsp turmeric",
      "1 tsp coriander powder",
      "1/2 tsp cumin powder",
      "1/2 tsp fenugreek seeds",
      "1 stalk curry leaves (optional)",
      "Salt to taste",
      "Fresh coriander for garnish",
      "Lime wedges for serving",
    ],
    instructions: [
      "Cut fish into large chunks and season lightly with salt and turmeric. Set aside.",
      "Heat oil in a deep pan over medium heat. Add fenugreek seeds and curry leaves (if using), cook for 30 seconds until fragrant.",
      "Add onions and cook until translucent (about 5 minutes).",
      "Add ginger, garlic and green chili. Cook for 1 minute.",
      "Stir in curry powder, coriander and cumin. Cook for 30 seconds to toast spices.",
      "Add tomatoes and cook until softened (about 3 minutes).",
      "Pour in coconut milk, bring to gentle simmer. Cook for 5 minutes.",
      "Gently add fish pieces. Simmer for 5-7 minutes until fish is cooked through.",
      "Adjust salt to taste. Garnish with fresh coriander.",
      "Serve hot with rice and lime wedges.",
    ],
    notes:
      "This fragrant curry showcases delicate fish flavors. For best results, use fresh fish and add it at the end to prevent overcooking. The curry tastes even better the next day as flavors develop. Adjust chili to your preferred heat level.",
    servings: 4,
    time: 30,
    category: "Seafood",
    img: "https://plus.unsplash.com/premium_photo-1712678665724-7c3faa117a2d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8ZmlzaCUyMGN1cnJ5fGVufDB8fDB8fHww",
    rating: 4.6,
  },
];

module.exports = { recipes };
